--! Previous: -
--! Hash: sha1:2f544d9a612fe13acf506919fec43be4bc2d5dec

CREATE EXTENSION IF NOT EXISTS citext;

DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS sessions CASCADE;
DROP TABLE IF EXISTS accounts CASCADE;
DROP TABLE IF EXISTS cookies CASCADE;

CREATE TABLE IF NOT EXISTS cookies (
  id TEXT NOT NULL,
  name TEXT NOT NULL,
  year INT NOT NULL,
  description TEXT NOT NULL,
  ordering INT NOT NULL,
  image_url TEXT,
  PRIMARY KEY (id, year),
  UNIQUE (year, ordering)
);

CREATE TABLE IF NOT EXISTS accounts (
  id CITEXT PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  account_id CITEXT REFERENCES accounts (id) ON DELETE SET NULL ON UPDATE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at TIMESTAMPTZ NOT NULL DEFAULT now() + CAST('30 days' AS INTERVAL)
);

CREATE TABLE IF NOT EXISTS reviews (
  id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  account_id CITEXT NOT NULL REFERENCES accounts (id) ON DELETE CASCADE ON UPDATE CASCADE,
  cookie_id TEXT NOT NULL,
  comment TEXT,
  year INT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  FOREIGN KEY (cookie_id, year) REFERENCES cookies (id, year) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS rankings (
  id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  account_id CITEXT NOT NULL REFERENCES accounts (id) ON DELETE CASCADE ON UPDATE CASCADE,
  cookie_id TEXT NOT NULL,
  year INT NOT NULL,
  ranking INT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (account_id, cookie_id, year),
  UNIQUE (account_id, year, ranking),
  FOREIGN KEY (cookie_id, year) REFERENCES cookies (id, year) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS comments (
  id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  account_id CITEXT NOT NULL REFERENCES accounts (id) ON DELETE CASCADE ON UPDATE CASCADE,
  review_id BIGINT NOT NULL REFERENCES comments (id) ON DELETE CASCADE ON UPDATE CASCADE,
  comment TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
